config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'
  root 'pages#main'

  get 'search', to: 'search#index', as: 'search'

  resources :abilities
  resources :types
  resources :pokemons
  get 'welcome', to: 'welcome#index'
  get 'about', to: 'welcome#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability < ApplicationRecord
  validates :ability_id, presence: true, uniqueness: true

  has_many :pokemon_abilities
  has_many :pokemons, through: :pokemon_abilities
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  validates :name, :height, :weight, presence: true
  validates :pokemon_id, presence: true, uniqueness: true

  has_many :pokemon_types
  has_many :types, through: :pokemon_types

  has_many :pokemon_abilities
  has_many :abilities, through: :pokemon_abilities

end

app/models/pokemon_ability.rb
class PokemonAbility < ApplicationRecord
  belongs_to :pokemon
  belongs_to :ability
end

app/models/pokemon_type.rb
class PokemonType < ApplicationRecord
  belongs_to :pokemon
  belongs_to :type
end

app/models/type.rb
class Type < ApplicationRecord
  validates :name, :generation, presence: true
  validates :type_id, presence: true, uniqueness: true

  has_many :pokemon_types
  has_many :pokemons, through: :pokemon_types
end

app/controllers/abilities_controller.rb
class AbilitiesController < ApplicationController
  before_action :set_ability, only: [:show, :edit, :update, :destroy]

  # GET /abilities
  # GET /abilities.json
  def index
    @abilities = Ability.page(params[:page]).per(10)
  end

  # GET /abilities/1
  # GET /abilities/1.json
  def show
  end

  # GET /abilities/new
  def new
    @ability = Ability.new
  end

  # GET /abilities/1/edit
  def edit
  end

  # POST /abilities
  # POST /abilities.json
  def create
    @ability = Ability.new(ability_params)

    respond_to do |format|
      if @ability.save
        format.html { redirect_to @ability, notice: 'Ability was successfully created.' }
        format.json { render :show, status: :created, location: @ability }
      else
        format.html { render :new }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abilities/1
  # PATCH/PUT /abilities/1.json
  def update
    respond_to do |format|
      if @ability.update(ability_params)
        format.html { redirect_to @ability, notice: 'Ability was successfully updated.' }
        format.json { render :show, status: :ok, location: @ability }
      else
        format.html { render :edit }
        format.json { render json: @ability.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abilities/1
  # DELETE /abilities/1.json
  def destroy
    @ability.destroy
    respond_to do |format|
      format.html { redirect_to abilities_url, notice: 'Ability was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ability
      @ability = Ability.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ability_params
      params.require(:ability).permit(:name, :generation, :ability_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.page(params[:page]).per(10)
  end

  def individual
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :height, :weight, :pokemon_id, :order)
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @search_terms = params[:q]
    @search_category = params[:p]

    pokeSearch = @search_category.to_ruby.arel_table
    @searchResults = @search_category.to_ruby.where(pokeSearch[:name].matches("%" + @search_terms + "%"))
  end
end

app/controllers/types_controller.rb
class TypesController < ApplicationController
  before_action :set_type, only: [:show, :edit, :update, :destroy]

  # GET /types
  # GET /types.json
  def index
    @types = Type.page(params[:page]).per(10)
  end

  # GET /types/1
  # GET /types/1.json
  def show
  end

  # GET /types/new
  def new
    @type = Type.new
  end

  # GET /types/1/edit
  def edit
  end

  # POST /types
  # POST /types.json
  def create
    @type = Type.new(type_params)

    respond_to do |format|
      if @type.save
        format.html { redirect_to @type, notice: 'Type was successfully created.' }
        format.json { render :show, status: :created, location: @type }
      else
        format.html { render :new }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /types/1
  # PATCH/PUT /types/1.json
  def update
    respond_to do |format|
      if @type.update(type_params)
        format.html { redirect_to @type, notice: 'Type was successfully updated.' }
        format.json { render :show, status: :ok, location: @type }
      else
        format.html { render :edit }
        format.json { render json: @type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /types/1
  # DELETE /types/1.json
  def destroy
    @type.destroy
    respond_to do |format|
      format.html { redirect_to types_url, notice: 'Type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type
      @type = Type.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_params
      params.require(:type).permit(:name, :type_id, :generation)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index

  end

  def about
    @test = 'test'
  end
end

app/helpers/abilities_helper.rb
module AbilitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/types_helper.rb
module TypesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/abilities/_form.html.erb
<%= form_with(model: ability, local: true) do |form| %>
  <% if ability.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(ability.errors.count, "error") %> prohibited this ability from being saved:</h2>

      <ul>
      <% ability.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :ability_name %>
  </div>

  <div class="field">
    <%= form.label :generation %>
    <%= form.text_field :generation, id: :ability_generation %>
  </div>

  <div class="field">
    <%= form.label :ability_id %>
    <%= form.number_field :ability_id, id: :ability_ability_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/abilities/edit.html.erb
<h1>Editing Ability</h1>

<%= render 'form', ability: @ability %>

<%= link_to 'Show', @ability %> |
<%= link_to 'Back', abilities_path %>

app/views/abilities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Abilities</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Generation</th>
      <th>Ability</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abilities.each do |ability| %>
      <tr>
        <td><%= ability.name.titlecase %></td>
        <td><%= ability.generation.titlecase %></td>
        <td><%= ability.ability_id %></td>
        <td><button class="btn-link"><%= link_to 'Show', ability %></button></td>
        <td><button class="btn-link"><%= link_to 'Edit', edit_ability_path(ability) %></button></td>
        <td><button class="btn-link"><%= link_to 'Destroy', ability, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%=  paginate @abilities, theme: 'twitter-bootstrap-4', pagination_class: "justify-content-center" %>
<br>

<%= link_to 'New Ability', new_ability_path %>

app/views/abilities/new.html.erb
<h1>New Ability</h1>

<%= render 'form', ability: @ability %>

<%= link_to 'Back', abilities_path %>

app/views/abilities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @ability.name.titlecase %>
</p>

<p>
  <strong>Generation:</strong>
  <%= @ability.generation %>
</p>

<p>
  <strong>Ability Number:</strong>
  <%= @ability.ability_id %>
</p>

<strong>Pokemon with the ability <%= @ability.name.titlecase %>:</strong>
<p>
  <% @pokebility = Ability.find_by_name(@ability.name).pokemons.pluck(:name) %>
  <% @pokebility.each do |pokebility| %>
    <%= pokebility.titlecase %>,
  <%  end %>
</p>

<%= link_to 'Edit', edit_ability_path(@ability) %> |
<%= link_to 'Back', abilities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- A grey horizontal navbar that becomes vertical on small screens -->
  <nav class="navbar navbar-expand-sm bg-light">

    <!-- Links -->
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/welcome">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/about">About</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/pokemons">Pokemon</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/abilities">Abilities</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/types">Types</a>
      </li>
      <li class="nav-item" class="navbar-right">
        <%= form_tag(search_path, method: "get") do %>
          <%= label_tag(:q, "Search for:") %>
          <%= text_field_tag(:q) %>
          <%= select_tag(:p, options_for_select([['Pokemon', 'Pokemon'], ['Ability', 'Ability'], ['Type', 'Type']])) %>
          <%= submit_tag("Search") %>
        <% end %>
      </li>
    </ul>
  </nav>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <title>PokemonDatabase</title>
  <%= csrf_meta_tags %>
<body>
<div class="container-fluid">
  <%= yield %>
</div>
</body>
</html>

app/views/pokemons/_form.html.erb
<%= form_with(model: pokemon, local: true) do |form| %>
  <% if pokemon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pokemon.errors.count, "error") %> prohibited this pokemon from being saved:</h2>

      <ul>
      <% pokemon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pokemon_name %>
  </div>

  <div class="field">
    <%= form.label :height %>
    <%= form.text_field :height, id: :pokemon_height %>
  </div>

  <div class="field">
    <%= form.label :weight %>
    <%= form.number_field :weight, id: :pokemon_weight %>
  </div>

  <div class="field">
    <%= form.label :pokemon_id %>
    <%= form.number_field :pokemon_id, id: :pokemon_pokemon_id %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.text_field :order, id: :pokemon_order %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pokemons/edit.html.erb
<h1>Editing Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Show', @pokemon %> |
<%= link_to 'Back', pokemons_path %>

app/views/pokemons/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-6">

<h1>Pokemon</h1>

<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Pokemon</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pokemons.each do |pokemon| %>
      <tr>

        <td><%= link_to pokemon.name.titlecase, pokemon_path(pokemon.id) %></td>
        <td><%= pokemon.height %></td>
        <td><%= pokemon.weight %></td>
        <td><%= pokemon.pokemon_id %></td>
        <td><%= pokemon.order %></td>
        <td><button class="btn-link"><%= link_to 'Show', pokemon %></button></td>
        <td><button class="btn-link"><%= link_to 'Edit', edit_pokemon_path(pokemon) %></button></td>
        <td><button class="btn-link"><%= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
   <%=  paginate @pokemons, theme: 'twitter-bootstrap-4', pagination_class: "justify-content-center" %>

<br>

<%= link_to 'New Pokemon', new_pokemon_path %>
  </div>
</div>

app/views/pokemons/new.html.erb
<h1>New Pokemon</h1>

<%= render 'form', pokemon: @pokemon %>

<%= link_to 'Back', pokemons_path %>

app/views/pokemons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pokemon.name.titlecase %>
</p>

<p>
  <strong>Height:</strong>
  <%= @pokemon.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @pokemon.weight %>
</p>

<p>
  <strong>Pokedex Number:</strong>
  <%= @pokemon.pokemon_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @pokemon.order %>
</p>

<strong>Types: </strong>
<p>
  <% @pokeTypes = Pokemon.find_by_name(@pokemon.name).types.pluck(:name) %>
  <% @pokeTypes.each do |pokeType| %>
    <%= pokeType.titlecase %></br>
  <%  end %>
</p>

<strong>Abilities: </strong>
<p>
  <% @pokebilities = Pokemon.find_by_name(@pokemon.name).abilities.pluck(:name) %>
  <% @pokebilities.each do |pokebility| %>
    <%= pokebility.titlecase %></br>
  <%  end %>
</p>

<%= link_to 'Edit', edit_pokemon_path(@pokemon) %> |
<%= link_to 'Back', pokemons_path %>

app/views/search/index.html.erb
<h1>Search Results</h1>



<p>Your search results for <%= @search_terms %> return <%= pluralize(@searchResults.size, 'result') %>.</p>
<ul>
<% @searchResults.each do |result| %>
  <li><%= link_to result.name, result %></li>
<% end %>
</ul>

app/views/types/_form.html.erb
<%= form_with(model: type, local: true) do |form| %>
  <% if type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(type.errors.count, "error") %> prohibited this type from being saved:</h2>

      <ul>
      <% type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :type_name %>
  </div>

  <div class="field">
    <%= form.label :type_id %>
    <%= form.number_field :type_id, id: :type_type_id %>
  </div>

  <div class="field">
    <%= form.label :generation %>
    <%= form.text_field :generation, id: :type_generation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/types/edit.html.erb
<h1>Editing Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Show', @type %> |
<%= link_to 'Back', types_path %>

app/views/types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Types</h1>

<table class = table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Generation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @types.each do |type| %>
      <tr>
        <td><%= type.name.titlecase %></td>
        <td><%= type.type_id %></td>
        <td><%= type.generation.titlecase %></td>
        <td><button class="btn-link"><%= link_to 'Show', type %></button></td>
        <td><button class="btn-link"><%= link_to 'Edit', edit_type_path(type) %></button></td>
        <td><button class="btn-link"><%= link_to 'Destroy', type, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%=  paginate @types, theme: 'twitter-bootstrap-4', pagination_class: "justify-content-center"  %>
<br>

<%= link_to 'New Type', new_type_path %>

app/views/types/new.html.erb
<h1>New Type</h1>

<%= render 'form', type: @type %>

<%= link_to 'Back', types_path %>

app/views/types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @type.name %>
</p>

<p>
  <strong>Type:</strong>
  <%= @type.type_id %>
</p>

<p>
  <strong>Generation:</strong>
  <%= @type.generation %>
</p>

<strong>Pokemon of Type <%= @type.name.titlecase %>:</strong>
<p>
  <% @pokeTypes = Type.find_by_name(@type.name).pokemons.pluck(:name) %>
  <% @pokeTypes.each do |pokeType| %>
  <%= pokeType.titlecase %>,
  <%  end %>
</p>

<%= link_to 'Edit', edit_type_path(@type) %> |
<%= link_to 'Back', types_path %>

app/views/welcome/about.html.erb
<div class="row">

  <div class="col-3"></div>
  <div class="col-6">
    <h1>Pokemon Database</h1>
    <p>I have chosen the Pokemon API as my data source for this project. This data source contains an overwhelming amount of data. As such, I've decided to include the following:</p>
    <h3>Tables:<h3>
    <p>Pokemon</p>
    <p>Types</p>
    <p>Abilities</p>
    <p>This will require two join tables:</p>
    <p>PokemonTypes</p>
    <p>PokemonAbilities</p>
    <p>Tables will have the following columns:</p>
    <p>Pokemon:</p>
    <p>name</p>
    <p>height</p>
    <p>weight</p>
    <p>pokemon_id</p>
    <p>order</p>
    <p>Types:</p>
    <p>name</p>
    <p>type_id</p>
    <p>generation</p>
    <p>Abilities:</p>
    <p>name</p>
    <p>generation</p>
    <p>ability_id</p>

    <p>These tables will contain Foreign Keys for the appropriate Join tables as well as ID Primary Keys. These will be generated by Rails.</p></div>
  <div class="col-3"></div>
</div>

app/views/welcome/index.html.erb
<div class="row">
  <div class="col-3"></div>
  <div class="col-6"><h1>Pokemon Database!</h1>
    <p>On this page you can find a listing of the first 160 pokemon, their abilities and their types. Please see the navigation links at the top of the page for more info.
    </p></div>
  <div class="col-3"></div>
</div>